POST /api/2.5/assets/863366f04c97422191da348f0776797d/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 352
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
X-Access-Token: 1ea3dbc940594a65a75589286f7afad7
DATA:
{
  "data": {
    "url": "http://localhost/get/aed1a56c6f494a05ab10f1c835003239?KeyID=172d32c8&Signature=dpWNbuMYhNRtb0B4Admyolz0emIv%2BWecLwesIc3rIemw2VFEPCK%2BWtZLHIKMt9%2BYeup6ymPBcxS6qid25i7EDA%3D%3D", 
    "title": "укр.doc", 
    "format": "application/msword", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "cancellationDetails"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/assets/863366f04c97422191da348f0776797d/documents/722caa1c29c143f5a5ee7f86bdddd4c3
X-Content-Type-Options: nosniff
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "asset_owner", 
    "title": "укр.doc", 
    "url": "http://localhost/get/aed1a56c6f494a05ab10f1c835003239?KeyID=172d32c8&Signature=cxwEo6tFApKOztFnfm4DQAIpi7OSQjYj32kBhMniEfKll%2FU4fODxYP4cuUJ1%252Bbn8gttFLYoITGEnE71ulmBPDg%253D%253D", 
    "format": "application/msword", 
    "documentOf": "asset", 
    "datePublished": "2019-02-01T11:03:56.417139+02:00", 
    "documentType": "cancellationDetails", 
    "dateModified": "2019-02-01T11:03:56.417160+02:00", 
    "id": "722caa1c29c143f5a5ee7f86bdddd4c3"
  }
}

