POST /api/2.4/assets/5c8cd4c766c74f60b25b2b9cdbfb8ef7/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 350
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
X-Access-Token: f9954df58b5c4f40a7ba11f1eae6063c
DATA:
{
  "data": {
    "url": "http://localhost/get/d569aea176a947e5abaf289e583cf96b?KeyID=9f887607&Signature=b4DgGl2WRakYWuEwJAZGbjbvN3Bu3cslLQJmcwXZzO%2FstWuhw75ZouJ5R7qEOU46OvwnAA1TO0s%2FRFWHAHOBBw%3D%3D", 
    "title": "укр.doc", 
    "format": "application/msword", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "cancellationDetails"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.4/assets/5c8cd4c766c74f60b25b2b9cdbfb8ef7/documents/c793551c2cdd483f89ac60d7ce36bc76
X-Content-Type-Options: nosniff
{
  "data": {
    "dateModified": "2018-05-22T13:40:23.403225+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://localhost/get/d569aea176a947e5abaf289e583cf96b?KeyID=9f887607&Signature=z3YrEXB8FwIR3ulRtu4lPjsEqD5kHKlH8rrCRG9kvJE6Ph%252Bjg%2FKou%252BxAsAhtlxFcKtYoAi8wMn0c1hf126IQDA%253D%253D", 
    "author": "asset_owner", 
    "documentOf": "asset", 
    "datePublished": "2018-05-22T13:40:23.403197+03:00", 
    "documentType": "cancellationDetails", 
    "title": "укр.doc", 
    "id": "c793551c2cdd483f89ac60d7ce36bc76"
  }
}

