POST /api/2.4/assets?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2734
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "assetType": "bounce", 
    "description": "Опис землі для космодрому", 
    "title": "Земля для космодрому", 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06121000-6", 
          "description": "Description"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }, 
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06121000-6", 
          "description": "Description"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2018-05-22T13:39:53.504199+03:00", 
        "decisionID": "1111-4"
      }
    ], 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256"
      }, 
      "address": {
        "countryName": "Україна"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.4/assets/5c8cd4c766c74f60b25b2b9cdbfb8ef7
X-Content-Type-Options: nosniff
{
  "access": {
    "token": "f9954df58b5c4f40a7ba11f1eae6063c"
  }, 
  "data": {
    "status": "draft", 
    "assetType": "bounce", 
    "documents": [
      {
        "title": "Інформація про оприлюднення інформаційного повідомлення", 
        "url": "https://prozorro.sale/info/ssp_details ", 
        "documentOf": "asset", 
        "datePublished": "2018-05-22T13:39:54.423035+03:00", 
        "documentType": "informationDetails", 
        "dateModified": "2018-05-22T13:39:54.423082+03:00", 
        "id": "e5796e629edd4477a730aa732a425f9d"
      }
    ], 
    "description": "Опис землі для космодрому", 
    "title": "Земля для космодрому", 
    "assetID": "UA-AR-DGF-2018-05-22-000001", 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "ca254ba6052947539d7bb26aaa163e8d", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }, 
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "1a1cf1d83a424e7284976caef828d680", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "dateModified": "2018-05-22T13:39:54.429965+03:00", 
    "owner": "broker", 
    "date": "2018-05-22T13:39:54.422540+03:00", 
    "decisions": [
      {
        "decisionDate": "2018-05-22T13:39:53.504199+03:00", 
        "decisionID": "1111-4"
      }
    ], 
    "id": "5c8cd4c766c74f60b25b2b9cdbfb8ef7", 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

