POST /api/2.5/assets?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2508
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "assetType": "bounce", 
    "description": "Опис землі для космодрому", 
    "title": "Земля для космодрому", 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06121000-6", 
          "description": "Description"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }, 
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06121000-6", 
          "description": "Description"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-02-01T11:03:55.184232+02:00", 
        "decisionID": "1111-4"
      }
    ], 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна"
      }, 
      "additionalContactPoints": [
        {
          "name": "name", 
          "email": "some@mail.com"
        }
      ]
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/assets/863366f04c97422191da348f0776797d
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "c00c113cedb147649671c027d897cded", 
    "token": "1ea3dbc940594a65a75589286f7afad7"
  }, 
  "data": {
    "status": "draft", 
    "assetType": "bounce", 
    "documents": [
      {
        "title": "Інформація про оприлюднення інформаційного повідомлення", 
        "url": "https://prozorro.sale/info/ssp_details", 
        "documentOf": "asset", 
        "datePublished": "2019-02-01T11:03:56.017442+02:00", 
        "documentType": "informationDetails", 
        "dateModified": "2019-02-01T11:03:56.017466+02:00", 
        "id": "bd5b68af29824668bded2ad5e9d1a469"
      }
    ], 
    "description": "Опис землі для космодрому", 
    "title": "Земля для космодрому", 
    "assetID": "UA-AR-DGF-2019-02-01-000001", 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "3d09b283ac1742ac8814ba8bdab16c00", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }, 
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "d4b3fe3628df4a21ab49b24d5ffd4dca", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "dateModified": "2019-02-01T11:03:56.020142+02:00", 
    "owner": "broker", 
    "date": "2019-02-01T11:03:56.017150+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-02-01T11:03:55.184232+02:00", 
        "decisionID": "1111-4", 
        "id": "a2799e7b35574c1d8854092b95e77fe6", 
        "decisionOf": "asset"
      }
    ], 
    "id": "863366f04c97422191da348f0776797d", 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна"
      }, 
      "additionalContactPoints": [
        {
          "name": "name", 
          "email": "some@mail.com"
        }
      ]
    }
  }
}

