PATCH /api/2.5/assets/f5cb190c7a5646ef8be8dd2c59065b6f HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Content-Length: 36
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "status": "verification"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "verification", 
    "assetType": "bounce", 
    "rectificationPeriod": {
      "startDate": "2019-02-01T11:03:56.638121+02:00"
    }, 
    "documents": [
      {
        "title": "Інформація про оприлюднення інформаційного повідомлення", 
        "url": "https://prozorro.sale/info/ssp_details", 
        "documentOf": "asset", 
        "datePublished": "2019-02-01T11:03:56.578102+02:00", 
        "documentType": "informationDetails", 
        "dateModified": "2019-02-01T11:03:56.578123+02:00", 
        "id": "02ed657c81f848c2b84847e5df695a0a"
      }
    ], 
    "description": "Опис землі для космодрому", 
    "title": "Земля для космодрому", 
    "assetID": "UA-AR-DGF-2019-02-01-000001", 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "51d63fd3c0b743ba921bb56d4576f7e5", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }, 
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "d4612104c3d24162af96028e36602193", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-02-01T11:03:55.184232+02:00", 
        "decisionID": "1111-4", 
        "id": "153216bcf4d545aba417a0d8d6a81892", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-02-01T11:03:56.733707+02:00", 
    "owner": "broker", 
    "date": "2019-02-01T11:03:56.733527+02:00", 
    "relatedProcesses": [
      {
        "type": "lot", 
        "id": "54657dec140f462ca28bf5b9c7b27518", 
        "relatedProcessID": "4d63fb44e1ed4fa895803644168e4268"
      }
    ], 
    "id": "f5cb190c7a5646ef8be8dd2c59065b6f", 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна"
      }, 
      "additionalContactPoints": [
        {
          "name": "name", 
          "email": "some@mail.com"
        }
      ]
    }
  }
}

