POST /api/2.5/assets?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2508
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
DATA:
{
  "data": {
    "assetType": "bounce", 
    "description": "Опис землі для космодрому", 
    "title": "Земля для космодрому", 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06121000-6", 
          "description": "Description"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }, 
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06121000-6", 
          "description": "Description"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-02-01T11:03:55.184232+02:00", 
        "decisionID": "1111-4"
      }
    ], 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна"
      }, 
      "additionalContactPoints": [
        {
          "name": "name", 
          "email": "some@mail.com"
        }
      ]
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea.openprocurement.net/api/2.5/assets/6df9770ea7794f09b437638c3a356836
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "66766dd2bcef4536907b9fbe55f04d05", 
    "token": "e2901be0e4a64a0c8b42879941b1732f"
  }, 
  "data": {
    "status": "draft", 
    "assetType": "bounce", 
    "documents": [
      {
        "title": "Інформація про оприлюднення інформаційного повідомлення", 
        "url": "https://prozorro.sale/info/ssp_details", 
        "documentOf": "asset", 
        "datePublished": "2019-02-01T11:03:56.193977+02:00", 
        "documentType": "informationDetails", 
        "dateModified": "2019-02-01T11:03:56.193998+02:00", 
        "id": "07e234f707324a648c9df1d7e8f0de79"
      }
    ], 
    "description": "Опис землі для космодрому", 
    "title": "Земля для космодрому", 
    "assetID": "UA-AR-DGF-2019-02-01-000002", 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "2f2f333b15d3464ca245536dc6b014e8", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }, 
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Description", 
          "id": "06121000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "17.21.1"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0e49ed227b9a4997a5f3867c8ce3d82c", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "dateModified": "2019-02-01T11:03:56.196216+02:00", 
    "owner": "broker", 
    "date": "2019-02-01T11:03:56.193724+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-02-01T11:03:55.184232+02:00", 
        "decisionID": "1111-4", 
        "id": "f87043f076414cbd906772349512605a", 
        "decisionOf": "asset"
      }
    ], 
    "id": "6df9770ea7794f09b437638c3a356836", 
    "assetCustodian": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна"
      }, 
      "additionalContactPoints": [
        {
          "name": "name", 
          "email": "some@mail.com"
        }
      ]
    }
  }
}

