PATCH /api/2.5/assets/863366f04c97422191da348f0776797d/items/3d09b283ac1742ac8814ba8bdab16c00 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 748
Content-Type: application/json
Host: lb.api-sandbox.registry.ea.openprocurement.net
X-Access-Token: 1ea3dbc940594a65a75589286f7afad7
DATA:
{
  "data": {
    "registrationDetails": {
      "status": "unknown"
    }, 
    "description": "футляри до державних нагород", 
    "classification": {
      "scheme": "CAV-PS", 
      "id": "06121000-6", 
      "description": "Description"
    }, 
    "additionalClassifications": [
      {
        "scheme": "UA-EDR", 
        "id": "17.21.1", 
        "description": "папір і картон гофровані, паперова й картонна тара"
      }
    ], 
    "address": {
      "countryName": "Ukraine"
    }, 
    "unit": {
      "code": "code"
    }, 
    "quantity": 42
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "registrationDetails": {
      "status": "unknown"
    }, 
    "description": "футляри до державних нагород", 
    "classification": {
      "scheme": "CAV-PS", 
      "description": "Description", 
      "id": "06121000-6"
    }, 
    "additionalClassifications": [
      {
        "scheme": "UA-EDR", 
        "description": "папір і картон гофровані, паперова й картонна тара", 
        "id": "17.21.1"
      }
    ], 
    "address": {
      "countryName": "Ukraine"
    }, 
    "id": "3d09b283ac1742ac8814ba8bdab16c00", 
    "unit": {
      "code": "code"
    }, 
    "quantity": 42
  }
}

